apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-infrastructure
type: Opaque
data:
  # -----------------------------------
  # MongoDB Credentials (Orders DB)
  # -----------------------------------
  mongo-root-user: cm9vdA==          # root
  mongo-root-pass: WTB1c3NlZjAwMA==  # Y0ussef000

  # -----------------------------------
  # MySQL Credentials (Products DB)
  # -----------------------------------
  mysql-root-user: cm9vdA==          # root
  mysql-root-pass: WTB1c3NlZjAwMA==  # Y0ussef000

  # -----------------------------------
  # PostgreSQL Credentials (Users DB)
  # -----------------------------------
  postgres-user: cG9zdGdyZXM=        # postgres
  postgres-pass: WTB1c3NlZjAwMA==    # Y0ussef000

  # -----------------------------------
  # RabbitMQ Credentials
  # -----------------------------------
  rabbitmq-user: Z3Vlc3Q=            # guest
  rabbitmq-pass: Z3Vlc3Q=            # guest