apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  namespace: ecommerce-infrastructure
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: ghcr.io/ym-harsha-ecommerce-microservices/ecommerce-users-api:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: DB_HOST
          value: "users-postgres-db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: postgres-user
        - name: DB_NAME
          value: "eCommerceUsers"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secrets
              key: postgres-pass