apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-db-service
  namespace: ecommerce-infrastructure
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: orders-mongo-db
