apiVersion: v1
kind: Service
metadata:
  name: users-api-service 
  namespace: ecommerce-infrastructure
  labels:
    app: users-api
spec:  
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: users-api